### ISSUE TITLE
ConfusionMatrix stats ValueError: too many boolean indices

### ISSUE THREAD

**Issue by VanZeidt** [scls19fr/pandas_confusion#9]
When I run the example:

```
from pandas_confusion import ConfusionMatrix
y_true = [600, 200, 200, 200, 200, 200, 200, 200, 500, 500, 500, 200, 200, 200, 200, 200, 200, 200, 200, 200]
y_pred = [100, 200, 200, 100, 100, 200, 200, 200, 100, 200, 500, 100, 100, 100, 100, 100, 100, 100, 500, 200]
cm = ConfusionMatrix(y_true, y_pred)
cm.stats()
```

I get the following error:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-d8b89bcacc68>", line 1, in <module>
    cm.stats()
  File "build\bdist.win-amd64\egg\pandas_confusion\__init__.py", line 424, in stats
    d_stats['class'] = self.stats_class
  File "build\bdist.win-amd64\egg\pandas_confusion\__init__.py", line 377, in stats_class
    binary_cm = self.binarize(cls)
  File "build\bdist.win-amd64\egg\pandas_confusion\__init__.py", line 310, in binarize
    binary_cm = BinaryConfusionMatrix(y_true_bin, y_pred_bin)
  File "build\bdist.win-amd64\egg\pandas_confusion\__init__.py", line 565, in __init__
    super(BinaryConfusionMatrix, self).__init__(*args, **kwargs)
  File "build\bdist.win-amd64\egg\pandas_confusion\__init__.py", line 98, in __init__
    df = df.loc[idx, idx.copy()].fillna(0) # if some columns or rows are missing
  File "C:\Python27\lib\site-packages\pandas\core\indexing.py", line 669, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Python27\lib\site-packages\pandas\core\indexing.py", line 258, in _getitem_tuple
    return self._multi_take(tup)
  File "C:\Python27\lib\site-packages\pandas\core\indexing.py", line 299, in _multi_take
    index = self._convert_for_reindex(tup[0], axis=0)
  File "C:\Python27\lib\site-packages\pandas\core\indexing.py", line 316, in _convert_for_reindex
    return labels[key]
  File "C:\Python27\lib\site-packages\pandas\core\index.py", line 380, in __getitem__
    result = arr_idx[key]
ValueError: too many boolean indices

print('%s %s' % (sys.executable or sys.platform, sys.version))
Python 2.7.4 (default, Apr  6 2013, 19:55:15) [MSC v.1500 64 bit (AMD64)]
```

The cm itself looks ok:

```
print(cm)
Predicted  100  200  500  600  __all__
Actual                                
100          0    0    0    0        0
200          9    6    1    0       16
500          1    1    1    0        3
600          1    0    0    0        1
__all__     11    7    2    0       20
```

I've tried with fewer values, but no avail:
```
y_true = [600, 200, 200]
y_pred = [100, 200, 200]
cm = ConfusionMatrix(y_true, y_pred)
print(cm)
Predicted  100  200  600  __all__
Actual                           
100          0    0    0        0
200          0    2    0        2
600          1    0    0        1
__all__      1    2    0        3
```

**Comment by scls19fr** [comment]
I've just try with Python 3.4 and 2.7 on Mac OS X .

Here is my results

    pc:pandas_confusion scls$ ipython
    Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Oct 20 2015, 14:27:51)
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: from pandas_confusion import ConfusionMatrix

    In [2]: y_true = [600, 200, 200, 200, 200, 200, 200, 200, 500, 500, 500, 200, 200, 200, 200, 200, 200, 200, 200, 200]

    In [3]: y_pred = [100, 200, 200, 100, 100, 200, 200, 200, 100, 200, 500, 100, 100, 100, 100, 100, 100, 100, 500, 200]

    In [4]: cm = ConfusionMatrix(y_true, y_pred)

    In [5]: cm.stats()
    Out[5]:
    OrderedDict([('cm', Predicted  100  200  500  600  __all__
                  Actual
                  100          0    0    0    0        0
                  200          9    6    1    0       16
                  500          1    1    1    0        3
                  600          1    0    0    0        1
                  __all__     11    7    2    0       20),
                 ('overall',
                  OrderedDict([('Accuracy', 0.34999999999999998),
                               ('95% CI',
                                (0.1539092047845412, 0.59218853453282805)),
                               ('No Information Rate', 'ToDo'),
                               ('P-Value [Acc > NIR]', 0.97858564435697903),
                               ('Kappa', 0.078014184397163108),
                               ("Mcnemar's Test P-Value", 'ToDo')])),
                 ('class',
                  Classes                                 100        200        500   600
                  Population                               20         20         20    20
                  P: Condition positive                     0         16          3     1
                  N: Condition negative                    20          4         17    19
                  Test outcome positive                    11          7          2     0
                  Test outcome negative                     9         13         18    20
                  TP: True Positive                         0          6          1     0
                  TN: True Negative                         9          3         16    19
                  FP: False Positive                       11          1          1     0
                  FN: False Negative                        0         10          2     1
                  TPR: (Sensitivity, hit rate, recall)    NaN      0.375   0.333333     0
                  TNR=SPC: (Specificity)                 0.45       0.75   0.941176     1
                  PPV: Pos Pred Value (Precision)           0   0.857143        0.5   NaN
                  NPV: Neg Pred Value                       1   0.230769   0.888889  0.95
                  FPR: False-out                         0.55       0.25  0.0588235     0
                  FDR: False Discovery Rate                 1   0.142857        0.5   NaN
                  FNR: Miss Rate                          NaN      0.625   0.666667     1
                  ACC: Accuracy                          0.45       0.45       0.85  0.95
                  F1 score                                  0   0.521739        0.4     0
                  MCC: Matthews correlation coefficient   NaN   0.104828   0.326732   NaN
                  Informedness                            NaN      0.125    0.27451     0
                  Markedness                                0  0.0879121   0.388889   NaN
                  Prevalence                                0        0.8       0.15  0.05
                  LR+: Positive likelihood ratio          NaN        1.5    5.66667   NaN
                  LR-: Negative likelihood ratio          NaN   0.833333   0.708333     1
                  DOR: Diagnostic odds ratio              NaN        1.8          8   NaN
                  FOR: False omission rate                  0   0.769231   0.111111  0.05)])

    In [6]:

    In [6]:
    Do you really want to exit ([y]/n)? y
    pc:pandas_confusion scls$ source activate py2
    discarding //anaconda/bin from PATH
    prepending //anaconda/envs/py2/bin to PATH
    (py2)pc:pandas_confusion scls$ ipython
    Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08)
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: from pandas_confusion import ConfusionMatrix

    In [2]: y_true = [600, 200, 200, 200, 200, 200, 200, 200, 500, 500, 500, 200, 200, 200, 200, 200, 200, 200, 200, 200]

    In [3]: y_pred = [100, 200, 200, 100, 100, 200, 200, 200, 100, 200, 500, 100, 100, 100, 100, 100, 100, 100, 500, 200]

    In [4]: cm = ConfusionMatrix(y_true, y_pred)

    In [5]: cm.stats()
    Out[5]:
    OrderedDict([(u'cm', Predicted  100  200  500  600  __all__
                  Actual
                  100          0    0    0    0        0
                  200          9    6    1    0       16
                  500          1    1    1    0        3
                  600          1    0    0    0        1
                  __all__     11    7    2    0       20),
                 (u'overall',
                  OrderedDict([(u'Accuracy', 0.34999999999999998),
                               (u'95% CI',
                                (0.1539092047845412, 0.59218853453282805)),
                               (u'No Information Rate', u'ToDo'),
                               (u'P-Value [Acc > NIR]', 0.97858564435697903),
                               (u'Kappa', 0.078014184397163108),
                               (u"Mcnemar's Test P-Value", u'ToDo')])),
                 (u'class',
                  Classes                                 100         200         500   600
                  Population                               20          20          20    20
                  P: Condition positive                     0          16           3     1
                  N: Condition negative                    20           4          17    19
                  Test outcome positive                    11           7           2     0
                  Test outcome negative                     9          13          18    20
                  TP: True Positive                         0           6           1     0
                  TN: True Negative                         9           3          16    19
                  FP: False Positive                       11           1           1     0
                  FN: False Negative                        0          10           2     1
                  TPR: (Sensitivity, hit rate, recall)    NaN       0.375   0.3333333     0
                  TNR=SPC: (Specificity)                 0.45        0.75   0.9411765     1
                  PPV: Pos Pred Value (Precision)           0   0.8571429         0.5   NaN
                  NPV: Neg Pred Value                       1   0.2307692   0.8888889  0.95
                  FPR: False-out                         0.55        0.25  0.05882353     0
                  FDR: False Discovery Rate                 1   0.1428571         0.5   NaN
                  FNR: Miss Rate                          NaN       0.625   0.6666667     1
                  ACC: Accuracy                          0.45        0.45        0.85  0.95
                  F1 score                                  0   0.5217391         0.4     0
                  MCC: Matthews correlation coefficient   NaN   0.1048285    0.326732   NaN
                  Informedness                            NaN       0.125   0.2745098     0
                  Markedness                                0  0.08791209   0.3888889   NaN
                  Prevalence                                0         0.8        0.15  0.05
                  LR+: Positive likelihood ratio          NaN         1.5    5.666667   NaN
                  LR-: Negative likelihood ratio          NaN   0.8333333   0.7083333     1
                  DOR: Diagnostic odds ratio              NaN         1.8           8   NaN
                  FOR: False omission rate                  0   0.7692308   0.1111111  0.05)])


I don't know what is going on under Windows

PS : please use block code to improve readability (3 back quotes or use indent)
https://help.github.com/articles/github-flavored-markdown/

**Comment by scls19fr** [comment]
```
import pandas as pd
In [8]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: None
IPython: 4.0.0
sphinx: 1.2.3
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.6
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 2.0.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.5
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.8
pymysql: None
psycopg2: None
```

Could you show version too ?

**Comment by VanZeidt** [comment]
```
import pandas as pd
pd.show_versions()
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-eaa3460ab7ab>", line 1, in <module>
    pd.show_versions()
AttributeError: 'module' object has no attribute 'show_versions'
```

I'll try to update Pandas now.

**Comment by scls19fr** [comment]
You can also try:

    pd.__version__

Are you using Anaconda Python ?

**Comment by VanZeidt** [comment]
Ok, I've updated to the latest version of Pandas, now it works, thanks!

```
import pandas as pd
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.4.final.0
python-bits: 64
OS: Windows
OS-release: 8
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.0
nose: 1.3.3
pip: 7.1.2
setuptools: None
Cython: None
numpy: 1.8.1
scipy: 0.12.0
statsmodels: None
IPython: 2.3.0
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
```

The results:
```
from pandas_confusion import ConfusionMatrix
y_true = [600, 200, 200, 200, 200, 200, 200, 200, 500, 500, 500, 200, 200, 200, 200, 200, 200, 200, 200, 200]
y_pred = [100, 200, 200, 100, 100, 200, 200, 200, 100, 200, 500, 100, 100, 100, 100, 100, 100, 100, 500, 200]
cm = ConfusionMatrix(y_true, y_pred)
print(cm)
Predicted  100  200  500  600  __all__
Actual                                
100          0    0    0    0        0
200          9    6    1    0       16
500          1    1    1    0        3
600          1    0    0    0        1
__all__     11    7    2    0       20
cm.print_stats()
Confusion Matrix:

Predicted  100  200  500  600  __all__
Actual                                
100          0    0    0    0        0
200          9    6    1    0       16
500          1    1    1    0        3
600          1    0    0    0        1
__all__     11    7    2    0       20


Overall Statistics:

Accuracy: 0.35
95% CI: (0.1539092047845412, 0.59218853453282805)
No Information Rate: ToDo
P-Value [Acc > NIR]: 0.978585644357
Kappa: 0.0780141843972
Mcnemar's Test P-Value: ToDo


Class Statistics:

Classes                                 100        200        500   600
Population                               20         20         20    20
P: Condition positive                     0         16          3     1
N: Condition negative                    20          4         17    19
Test outcome positive                    11          7          2     0
Test outcome negative                     9         13         18    20
TP: True Positive                         0          6          1     0
TN: True Negative                         9          3         16    19
FP: False Positive                       11          1          1     0
FN: False Negative                        0         10          2     1
TPR: (Sensitivity, hit rate, recall)    NaN      0.375   0.333333     0
TNR=SPC: (Specificity)                 0.45       0.75   0.941176     1
PPV: Pos Pred Value (Precision)           0   0.857143        0.5   NaN
NPV: Neg Pred Value                       1   0.230769   0.888889  0.95
FPR: False-out                         0.55       0.25  0.0588235     0
FDR: False Discovery Rate                 1   0.142857        0.5   NaN
FNR: Miss Rate                          NaN      0.625   0.666667     1
ACC: Accuracy                          0.45       0.45       0.85  0.95
F1 score                                  0   0.521739        0.4     0
MCC: Matthews correlation coefficient   NaN   0.104828   0.326732   NaN
Informedness                            NaN      0.125    0.27451     0
Markedness                                0  0.0879121   0.388889   NaN
Prevalence                                0        0.8       0.15  0.05
LR+: Positive likelihood ratio          NaN        1.5    5.66667   NaN
LR-: Negative likelihood ratio          NaN   0.833333   0.708333     1
DOR: Diagnostic odds ratio              NaN        1.8          8   NaN
FOR: False omission rate                  0   0.769231   0.111111  0.05
```
